name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0+4

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts:
  qr_code_scanner:
  graphql:
  graphql_flutter:
  photo_view:
  camera: ^0.9.4+5
  pinch_zoom:
  shared_preferences:
  

flutter:
  uses-material-design: true
  assets:
    - images/logo.png
    - images/undraw.png
    - images/logo1.png
    - images/logo2.png
    - images/avatar.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
